file:main.cpp
	g++ $+ -o $@ -lopencv_videoio -lopencv_core -lopencv_highgui -lswscale -lavutil -std=c++11 -I/usr/local/Cellar/opencv/3.3.0_3/include -I/usr/local/Cellar/ffmpeg/3.4/include -L/usr/local/Cellar/ffmpeg/3.4/lib -L/usr/local/Cellar/opencv/3.3.0_3/lib
